[package]
name = "mc2wasm"
version = "0.1.0"
authors = ["Andrés Testi <andres.a.testi.-nd@disney.com>"]
edition = "2018"

[dependencies]
downcast-rs = "1.0"
lazy_static = "1.4.0"

[dependencies.nom]
version = "^5"
features = ["regexp", "regexp_macros"]



